name: Genera articoli Motori

on:
  workflow_dispatch:
    inputs:
      category:
        description: "news | tests | guides"
        required: true
        default: "news"
      prompt:
        description: "Tema/brief (IT). Es: SUV elettrico ricarica veloce 2025"
        required: true
      publish_branch:
        description: "Branch di destinazione"
        required: true
        default: "main"

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm install openai@4

      - name: Generate content
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          UNSPLASH_ACCESS_KEY: ${{ secrets.UNSPLASH_ACCESS_KEY }}
          CATEGORY: ${{ github.event.inputs.category }}
          USER_PROMPT: ${{ github.event.inputs.prompt }}
        run: node scripts/generate-content.mjs

      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: contenuto auto (${{ github.event.inputs.category }})"
            git push origin ${{ github.event.inputs.publish_branch }}
          fi
